name: Build, Test, and Deploy to Azure and Plesk

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_APP_NAME: CircuitsByCarl
  DEPLOY_PACKAGE: package.zip
  
jobs:
  build-and-test:
    name: Build and Test Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Run Tests
        run: npm test

      - name: Archive Build Output
        run: zip -r ${{ env.DEPLOY_PACKAGE }} ./dist ./package.json ./package-lock.json ./node_modules

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ${{ env.DEPLOY_PACKAGE }}

  deploy-to-azure:
    name: Deploy to Azure Web App
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: .

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ${{ env.DEPLOY_PACKAGE }}